# Generated by Django 5.1.3 on 2024-11-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_arquivo_usuario_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='usuario_chave',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
